[workspace]
members = [
    "norpc",
    "norpc-macros",
    "example/hello-world",
    "example/kvstore",
    "example/concurrent-message",
    "example/rate-limit",
    "benchmark/noop",
    "benchmark/noop-raw",
    "benchmark/noop-tarpc",
]