[workspace]
members = [
    "norpc",
    "norpc-macros",
    "example/hello-world",
    "example/hello-world-no-send",
    "example/kvstore",
    "example/concurrency",
    "example/rate-limit",
    "example/streaming",
    "benchmark/noop",
    "benchmark/noop-tarpc",
]