[package]
name = "norpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "*", features = ["full"] }
tower-service = "*"
tower = { version = "*", features = ["full"] }
async-trait = "*"
futures = "*"
anyhow = "*"
thiserror = "*"
nom = "7"
itertools = "*"