[package]
name = "norpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
tower-service = "0.3"
tower = { version = "0.4", features = ["full"] }
async-trait = "0.1"
futures = "0.3"
anyhow = "1"
thiserror = "1"
nom = "7"
itertools = "0.10"