[package]
name = "norpc"
version = "0.3.0"
authors = ["Akira Hayakawa <ruby.wktk@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Framework for in-process microservices"
repository = "https://github.com/akiradeveloper/norpc"
readme = "../README.md"
categories = ["concurrency"]
keywords = ["rpc", "microservices", "async"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["sync", "rt"] }
tower-service = "0.3"
tower = "0.4"
async-trait = "0.1"
nom = "7"
itertools = "0.10"
futures = "0.3"
thiserror = "1"