[package]
name = "norpc-macros"
authors = ["Akira Hayakawa <ruby.wktk@gmail.com>"]
version = "0.4.0"
edition = "2021"
license = "MIT"
description = "Code generator for norpc"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1", features = ["full"] }
quote = "1"
itertools = "0.10"